---

- debug: var=myid

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- service: name=zookeeper state=restarted

- name: Wait for Zookeeper to start
  wait_for: host=127.0.0.1 port=2181 delay=5 state=present

- name: Check that zookeeper started correctly
  shell: echo ruok | nc 127.0.0.1 2181
  register: zk_ruok

- assert:
    that:
      - "'imok' in zk_ruok.stdout"

- name: Check that zookeeper is not standalone
  shell: echo stat | nc 127.0.0.1 2181 | grep Mode
  register: zk_stat

- name: Check if zk node is either leader or follower
  fail: msg="Zookeeper node should be either leader or follower"
  when:
  - num_nsdb_nodes > 1
  - not "'follower' in zk_stat.stdout or 'leader' in zk_stat.stdout"

- name: Check if zk node is standalone
  fail: msg="Zookeeper node should be standalone"
  when:
  - num_nsdb_nodes == 1
  - not "'standalone' in zk_stat.stdout"
