---


- name: Get public net ID
  shell: neutron net-list | grep public | awk '{ print $2 }'
  register: public_network
  environment:
    OS_USERNAME: admin
    OS_TENANT_NAME: admin
    OS_PASSWORD: "{{ admin_pass }}"
    OS_AUTH_URL: http://127.0.0.1:35357/v2.0/

- name: Set up fake uplink
  script: create_fake_uplink_l2.sh "{{ public_network.stdout }}" 200.200.200.0/24  200.200.200.1 
