#
# Midonet Ansible Quickstart
# Copyright (C) 2015  Midokura SARL
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
---
# This playbook deploys the whole application stack in this site.

- hosts: bcn11
  vars_files:
  - vars/{{ deploy }}.yml
  - vars/defaults.yml
  - "{{ os_settings | default('vars/os_settings.yml') }}"
  become: yes
  pre_tasks:
  roles:
  - role: common
    http_proxy: ""
  - midorepo
  - role: zookeeper
    myid: 1
  - cassandra
  - mysql
  - rabbitmq
  - keystone
  - glance
  - neutron-server
  - neutron-dhcp-agent
  - nova-conductor
  - nova-consoleauth
  - nova-api
  - nova-novncproxy
  - nova-scheduler
  - horizon
  - midorepo
  - midonet-cluster
  - role: nova-compute
    vncserver_proxy_address: "{{ ansible_ssh_host }}" # trick for floating ip
  - role: controller_post
    public_ip: "{{ ansible_ssh_host }}"
  - role: compute_post
    controller_host: "bcn11"
    midonet_api_hostname: "{{ mgmt_ip }}"
    keystone_hostname: "{{ mgmt_ip }}"
  - role: midolman
    agent_template: 'agent-compute-medium'
    midonet_api_hostname: "{{ mgmt_ip }}"
  # - fake_uplink
