---
- name: Delete instances
  hosts: localhost
  connection: local
  vars_files:
  - vars/{{ deploy }}.yml
  - vars/defaults.yml
  - - "{{ os_settings | default('vars/os_settings.yml') }}"
  tasks:
  - include: tasks/delete-instances.yml
