#
# Copyright 2015 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- name: Configure midonet cluster config file
  template: src=midonet.conf.j2 dest=/etc/midonet/midonet.conf

- name: Set loglevel to debug in midonet-cluster.conf (if loglevel==debug)
  replace:
    dest: '/etc/midonet-cluster/logback.xml'
    regexp:  '    <root level=".*">'
    replace: '    <root level="DEBUG">'
  when: loglevel == 'debug'

- name: mn-conf default template
  template: src=default.template.j2 dest=/etc/midonet/default.template owner=root group=root

- name: Apply default mn-conf template (for all nodes)
  shell: cat /etc/midonet/default.template | mn-conf set -t default
  retries: 5
  delay: 10

- name: mn-conf metadata template
  template: src=metadata.template.j2 dest=/etc/midonet/metadata.template owner=root group=root
  when: midonet_metadata is defined and midonet_metadata|bool

- name: Apply metadata mn-conf template
  shell: cat /etc/midonet/metadata.template | mn-conf set -t default
  when: midonet_metadata is defined and midonet_metadata|bool
  retries: 5
  delay: 10

- name: Ensure midonet-cluster is restarted
  service: name=midonet-cluster state=restarted
