---

- name: Configure midonet cluster config file
  template: src=midonet.conf.j2 dest=/etc/midonet/midonet.conf

- name: Set loglevel to debug in midonet-cluster.conf (if loglevel==debug)
  replace:
    dest: '/etc/midonet-cluster/logback.xml'
    regexp:  '    <root level=".*">'
    replace: '    <root level="DEBUG">'
  when: loglevel == 'debug'

- name: mn-conf default template
  template: src=default.template.j2 dest=/etc/midonet/default.template owner=root group=root

- name: Apply default mn-conf template (for all nodes)
  shell: cat /etc/midonet/default.template | mn-conf set -t default
  retries: 5
  delay: 10

- name: mn-conf metadata template
  template: src=metadata.template.j2 dest=/etc/midonet/metadata.template owner=root group=root
  when: midonet_metadata is defined and midonet_metadata|bool

- name: Apply metadata mn-conf template
  shell: cat /etc/midonet/metadata.template | mn-conf set -t default
  when: midonet_metadata is defined and midonet_metadata|bool
  retries: 5
  delay: 10

- name: Ensure midonet-cluster is restarted
  service: name=midonet-cluster state=restarted
