---

- name: Install Midonet Cluster
  yum: name=midonet-cluster state=present
  when: mm_version is not defined or mm_version == "default"

- name: Install Midonet Cluster
  yum: name=midonet-cluster-{{mm_version}} state=present
  when: mm_version is defined and mm_version != "default"
