#
# Copyright 2015 Midokura SARL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: setup the ceilometer config file
  ini_file: dest=/etc/ceilometer/ceilometer.conf
            section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
    - { section: "publisher", option: "telemetry_secret", value: "{{ ceilometer_secret }}" }
    - { section: "DEFAULT", option: "rpc_backend", value: "rabbit" }
    - { section: "oslo_messaging_rabbit", option: "rabbit_host", value: "{{ mgmt_ip }}" }
    - { section: "oslo_messaging_rabbit", option: "rabbit_userid", value: "guest" }
    - { section: "oslo_messaging_rabbit", option: "rabbit_password", value: "{{ admin_password }}" }
    - { section: "keystone_authtoken", option: "auth_uri", value: "http://{{ mgmt_ip }}:5000/v2.0" }
    - { section: "keystone_authtoken", option: "identity_uri", value: "http://{{ mgmt_ip }}:35357" }
    - { section: "keystone_authtoken", option: "admin_tenant_name", value: "service" }
    - { section: "keystone_authtoken", option: "admin_user", value: "ceilometer" }
    - { section: "keystone_authtoken", option: "admin_password", value: "{{ admin_password }}" }
    - { section: "service_credentials", option: "os_auth_url", value: "http://{{ mgmt_ip }}:5000/v2.0" }
    - { section: "service_credentials", option: "os_username", value: "ceilometer" }
    - { section: "service_credentials", option: "os_tenant_name", value: "service" }
    - { section: "service_credentials", option: "os_password", value: "{{ admin_password }}" }
    - { section: "service_credentials", option: "os_endpoint_type", value: "internalURL" }

- name: Tell nova compute to use ceilometer
  ini_file: dest=/etc/nova/nova.conf
            section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:  
    - { section: "DEFAULT", option: "instance_usage_audit", value: "True" }
    - { section: "DEFAULT", option: "instance_usage_audit_period", value: "hour" }
    - { section: "DEFAULT", option: "notify_on_state_change", value: "vm_and_task_state" }
    - { section: "DEFAULT", option: "notification_driver", value: "messagingv2" }
    
- name: enable ceilometer services
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - openstack-ceilometer-compute

- name: restart nova compute
  service: name=openstack-nova-compute state=restarted



