---


- name: Set facts
  set_fact:
    nova_compute_service: "nova-compute"
    libvirt_service: "libvirt-bin"
    nova_compute_conf: "/etc/nova/nova-compute.conf"
    libvirt_conf: "/etc/libvirt/libvirtd.conf"
    libvirt_init: "/etc/default/libvirt-bin"
  when: ansible_os_family == 'Debian'

- name: Set facts
  set_fact:
    nova_compute_service: "openstack-nova-compute"
    libvirt_service: "libvirtd"
    nova_compute_conf: "/etc/nova/nova.conf"
    libvirt_conf: "/etc/libvirt/libvirtd.conf"
    libvirt_init: "/etc/sysconfig/libvirtd"
  when: ansible_os_family == 'RedHat'
