---


- name: Check if tunnel zone exists
  shell: "midonet-cli -e tunnel-zone list | grep {{ tzone_type }}"
  register: midonet_tzone_exists
  failed_when: midonet_tzone_exists.rc >= 2

- name: Create tunnel zone
  shell: "midonet-cli -e tunnel-zone create name {{ tzone_type }} type {{ tzone_type }} "
  when: midonet_tzone_exists | failed

- name: Get tunnel zone id
  shell: "midonet-cli -e tunnel-zone list | grep {{ tzone_type }} | cut -d ' ' -f 2"
  register: midonet_tzone

- name: Get host id
  shell: "midonet-cli -e host list | grep {{ ansible_hostname }} | cut -d ' ' -f 2"
  register: midonet_hostid
  until: midonet_hostid.stdout != ""
  retries: 20
  delay: 10

- name: Check if host is already in tunnel zone
  shell: "midonet-cli -e tunnel-zone {{ midonet_tzone.stdout }} list member | grep {{ midonet_hostid.stdout }}"
  register: midonet_tzone_member_exists
  failed_when: midonet_tzone_member_exists.rc >= 2

- name: Add host to tunnel zone
  shell: "midonet-cli -e tunnel-zone {{ midonet_tzone.stdout }} add member host {{ midonet_hostid.stdout }} address {{ mgmt_ip }}"
  when:
    - midonet_tzone_member_exists | failed
